In [1]:
import os
import numpy as np
import pandas as pd
import pandas_gbq
from google.cloud import bigquery
%load_ext google.cloud.bigquery

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = '../zori-data-extr-be793d5c3325.json'

# Set your default project here
pandas_gbq.context.project = 'bigquery-public-data'
pandas_gbq.context.dialect = 'standard'

In [3]:
%%bigquery --use_rest_api ACS_2018
SELECT *
FROM `bigquery-public-data.census_bureau_acs.zip_codes_2018_5yr`

Query complete after 0.03s: 100%|██████████| 2/2 [00:00<00:00, 310.36query/s]
Downloading: 100%|██████████| 33120/33120 [00:05<00:00, 6462.89rows/s]

In [7]:
pd.set_option('display.max_columns', None)
ACS_2018.head()

,geo_id,do_date,total_pop,households,male_pop,female_pop,median_age,male_under_5,male_5_to_9,male_10_to_14,male_15_to_17,male_18_to_19,male_20,male_21,male_22_to_24,male_25_to_29,male_30_to_34,male_35_to_39,male_40_to_44,male_45_to_49,male_50_to_54,male_55_to_59,male_65_to_66,male_67_to_69,male_70_to_74,male_75_to_79,male_80_to_84,male_85_and_over,female_under_5,female_5_to_9,female_10_to_14,female_15_to_17,female_18_to_19,female_20,female_21,female_22_to_24,female_25_to_29,female_30_to_34,female_35_to_39,female_40_to_44,female_45_to_49,female_50_to_54,female_55_to_59,female_60_to_61,female_62_to_64,female_65_to_66,female_67_to_69,female_70_to_74,female_75_to_79,female_80_to_84,female_85_and_over,white_pop,population_1_year_and_over,population_3_years_over,pop_5_years_over,pop_15_and_over,pop_16_over,pop_25_years_over,pop_25_64,pop_never_married,pop_now_married,pop_separated,pop_widowed,pop_divorced,not_us_citizen_pop,black_pop,asian_pop,hispanic_pop,amerindian_pop,other_race_pop,two_or_more_races_pop,hispanic_any_race,not_hispanic_pop,asian_male_45_54,asian_male_55_64,black_male_45_54,black_male_55_64,hispanic_male_45_54,hispanic_male_55_64,white_male_45_54,white_male_55_64,median_income,income_per_capita,income_less_10000,income_10000_14999,income_15000_19999,income_20000_24999,income_25000_29999,income_30000_34999,income_35000_39999,income_40000_44999,income_45000_49999,income_50000_59999,income_60000_74999,income_75000_99999,income_100000_124999,income_125000_149999,income_150000_199999,income_200000_or_more,pop_determined_poverty_status,poverty,gini_index,housing_units,renter_occupied_housing_units_paying_cash_median_gross_rent,owner_occupied_housing_units_lower_value_quartile,owner_occupied_housing_units_median_value,owner_occupied_housing_units_upper_value_quartile,occupied_housing_units,housing_units_renter_occupied,vacant_housing_units,vacant_housing_units_for_rent,vacant_housing_units_for_sale,dwellings_1_units_detached,dwellings_1_units_attached,dwellings_2_units,dwellings_3_to_4_units,dwellings_5_to_9_units,dwellings_10_to_19_units,dwellings_20_to_49_units,dwellings_50_or_more_units,mobile_homes,housing_built_2005_or_later,housing_built_2000_to_2004,housing_built_1939_or_earlier,median_year_structure_built,married_households,nonfamily_households,family_households,households_public_asst_or_food_stamps,male_male_households,female_female_households,children,children_in_single_female_hh,median_rent,percent_income_spent_on_rent,rent_burden_not_computed,rent_over_50_percent,rent_40_to_50_percent,rent_35_to_40_percent,rent_30_to_35_percent,rent_25_to_30_percent,rent_20_to_25_percent,rent_15_to_20_percent,rent_10_to_15_percent,rent_under_10_percent,owner_occupied_housing_units,million_dollar_housing_units,mortgaged_housing_units,different_house_year_ago_different_city,different_house_year_ago_same_city,families_with_young_children,two_parent_families_with_young_children,two_parents_in_labor_force_families_with_young_children,two_parents_father_in_labor_force_families_with_young_children,two_parents_mother_in_labor_force_families_with_young_children,two_parents_not_in_labor_force_families_with_young_children,one_parent_families_with_young_children,father_one_parent_families_with_young_children,father_in_labor_force_one_parent_families_with_young_children,commute_less_10_mins,commute_10_14_mins,commute_15_19_mins,commute_20_24_mins,commute_25_29_mins,commute_30_34_mins,commute_35_44_mins,commute_60_more_mins,commute_45_59_mins,commuters_16_over,walked_to_work,worked_at_home,no_car,no_cars,one_car,two_cars,three_cars,four_more_cars,aggregate_travel_time_to_work,commuters_by_public_transportation,commuters_by_bus,commuters_by_car_truck_van,commuters_by_carpool,commuters_by_subway_or_elevated,commuters_drove_alone,group_quarters,associates_degree,bachelors_degree,high_school_diploma,less_one_year_college,masters_degree,one_year_more_college,less_than_high_school_graduate,high_school_including_ged,bachelors_degree_2,bachelors_degree_or_higher_25_64,graduate_professional_degree,some_college_and_associates_degree,male_45_64_associates_degree,male_45_64_bachelors_degree,male_45_64_graduate_degree,male_45_64_less_than_9_grade,male_45_64_grade_9_12,male_45_64_high_school,male_45_64_some_college,male_45_to_64,employed_pop,unemployed_pop,pop_in_labor_force,not_in_labor_force,workers_16_and_over,armed_forces,civilian_labor_force,employed_agriculture_forestry_fishing_hunting_mining,employed_arts_entertainment_recreation_accommodation_food,employed_construction,employed_education_health_social,employed_finance_insurance_real_estate,employed_information,employed_manufacturing,employed_other_services_not_public_admin,employed_public_administration,employed_retail_trade,employed_science_management_admin_waste,employed_transportation_warehousing_utilities,employed_wholesale_trade,occupation_management_arts,occupation_natural_resources_construction_maintenance,occupation_production_transportation_material,occupation_sales_office,occupation_services,management_business_sci_arts_employed,sales_office_employed,in_grades_1_to_4,in_grades_5_to_8,in_grades_9_to_12,in_school,in_undergrad_college,speak_only_english_at_home,speak_spanish_at_home,speak_spanish_at_home_low_english
0,87537,2014-01-01,2510.0,856.0,1283.0,1227.0,42.1,58.0,75.0,87.0,52.0,13.0,7.0,10.0,16.0,38.0,84.0,9.0,61.0,43.0,133.0,15.0,55.0,40.0,40.0,69.0,8.0,25.0,115.0,229.0,93.0,29.0,0.0,0.0,18.0,56.0,19.0,133.0,100.0,46.0,9.0,60.0,42.0,58.0,51.0,17.0,75.0,25.0,37.0,4.0,11.0,329.0,NaN,2361.0,NaN,NaN,NaN,1652.0,NaN,NaN,NaN,NaN,NaN,NaN,82.0,6.0,0.0,2134.0,32.0,0.0,9.0,2134.0,376.0,0.0,0.0,0.0,0.0,133.0,355.0,40.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1443.0,623.0,104700.0,144200.0,246900.0,856.0,188.0,587.0,86.0,2.0,599.0,3.0,3.0,36.0,0.0,0.0,0.0,0.0,802.0,0.0,2.0,55.0,1979.0,288.0,326.0,530.0,NaN,1.0,0.0,738.0,150.0,428.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,668.0,3.0,349.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,143.0,168.0,198.0,438.0,62.0,307.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,52.0,0.0,41.0,7.0,37.0,399.0,536.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,304.0,171.0,80.0,593.0,20.0,NaN,NaN,NaN
1,87017,2014-01-01,346.0,112.0,150.0,196.0,50.9,0.0,0.0,12.0,10.0,9.0,0.0,0.0,0.0,0.0,14.0,0.0,0.0,35.0,0.0,30.0,10.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,15.0,5.0,32.0,0.0,0.0,8.0,0.0,0.0,11.0,14.0,0.0,9.0,23.0,0.0,9.0,0.0,0.0,0.0,0.0,70.0,0.0,33.0,NaN,346.0,NaN,NaN,NaN,255.0,NaN,NaN,NaN,NaN,NaN,NaN,61.0,0.0,52.0,261.0,0.0,0.0,0.0,261.0,85.0,4.0,0.0,0.0,0.0,31.0,56.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,240.0,1045.0,114200.0,170800.0,199700.0,112.0,23.0,128.0,6.0,5.0,111.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,129.0,0.0,0.0,0.0,1976.0,45.0,36.0,76.0,NaN,0.0,0.0,42.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,89.0,0.0,31.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,20.0,161.0,28.0,6.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,6.0,0.0,0.0,11.0,60.0,14.0,91.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,27.0,15.0,96.0,40.0,NaN,NaN,NaN
2,87528,2014-01-01,3505.0,727.0,1758.0,1747.0,27.9,260.0,194.0,159.0,121.0,38.0,5.0,0.0,112.0,202.0,56.0,106.0,66.0,37.0,111.0,89.0,12.0,11.0,85.0,10.0,9.0,0.0,151.0,165.0,189.0,82.0,45.0,1.0,57.0,44.0,106.0,110.0,103.0,35.0,173.0,181.0,104.0,22.0,41.0,21.0,44.0,55.0,13.0,5.0,0.0,84.0,NaN,3311.0,NaN,NaN,NaN,1882.0,NaN,NaN,NaN,NaN,NaN,NaN,34.0,16.0,0.0,775.0,2566.0,10.0,54.0,775.0,2730.0,0.0,0.0,0.0,7.0,10.0,37.0,0.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1024.0,501.0,43800.0,92700.0,163800.0,727.0,227.0,297.0,18.0,0.0,684.0,2.0,64.0,19.0,5.0,0.0,0.0,0.0,250.0,23.0,26.0,0.0,1984.0,236.0,274.0,453.0,NaN,0.0,0.0,1321.0,568.0,364.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,500.0,0.0,66.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,142.0,115.0,678.0,86.0,78.0,511.0,NaN,NaN,NaN,NaN,NaN,NaN,22.0,37.0,0.0,3.0,32.0,149.0,69.0,312.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,293.0,266.0,298.0,1237.0,138.0,NaN,NaN,NaN
3,87533,2014-01-01,133.0,58.0,49.0,84.0,25.8,0.0,12.0,8.0,4.0,8.0,0.0,0.0,0.0,3.0,3.0,3.0,5.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,22.0,0.0,3.0,0.0,0.0,0.0,2.0,2.0,6.0,14.0,9.0,0.0,0.0,7.0,0.0,3.0,3.0,0.0,0.0,0.0,3.0,4.0,7.0,NaN,133.0,NaN,NaN,NaN,68.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,126.0,0.0,0.0,0.0,126.0,7.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68.0,738.0,13400.0,17900.0,NaN,58.0,19.0,10.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60.0,0.0,0.0,2.0,1993.0,8.0,36.0,22.0,NaN,0.0,0.0,55.0,37.0,347.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.0,0.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,6.0,9.0,12.0,15.0,3.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,3.0,0.0,0.0,0.0,0.0,0.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,8.0,7.0,58.0,3.0,NaN,NaN,NaN
4,87511,2014-01-01,2896.0,787.0,1177.0,1719.0,36.0,142.0,63.0,44.0,123.0,0.0,92.0,0.0,0.0,28.0,2.0,49.0,122.0,36.0,196.0,44.0,5.0,64.0,29.0,0.0,48.0,0.0,135.0,255.0,65.0,98.0,3.0,128.0,2.0,125.0,52.0,86.0,52.0,77.0,46.0,90.0,259.0,0.0,20.0,68.0,29.0,5.0,4.0,120.0,0.0,324.0,NaN,2756.0,NaN,NaN,NaN,1621.0,NaN,NaN,NaN,NaN,NaN,NaN,102.0,37.0,0.0,2532.0,0.0,0.0,0.0,2532.0,364.0,0.0,0.0,0.0,0.0,200.0,134.0,32.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1295.0,540.0,81400.0,134800.0,172100.0,787.0,227.0,508.0,0.0,46.0,445.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,846.0,0.0,48.0,4.0,1990.0,440.0,155.0,632.0,NaN,0.0,0.0,925.0,269.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,560.0,0.0,335.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,165.0,112.0,374.0,313.0,60.0,428.0,NaN,NaN,NaN,NaN,NaN,NaN,50.0,45.0,0.0,0.0,49.0,141.0,81.0,366.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,263.0,107.0,163.0,1008.0,279.0,NaN,NaN,NaN